[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "simple_producer"
path = "simple_producer.rs"

[[bin]]
name = "simple_consumer"
path = "simple_consumer.rs"

[[bin]]
name = "partitioner_producer"
path = "partitioner_producer.rs"

[[bin]]
name = "subscription_consumer"
path = "subscription_consumer.rs"

[[bin]]
name = "consumer_group"
path = "consumer_group.rs"

[[bin]]
name = "producer_for_groups"
path = "producer_for_groups.rs"

[dependencies]
client = { path = "../client" }
protocol = { path = "../protocol" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
